name: insightme
description: Track anything about your life.

# The following defines the version and build number for your application.
version: 1.0.9+10

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+3 # SQLite
  path_provider: ^2.0.2 # SQLite
  file_picker: ^3.0.3 # csv file

  flutter_charts: ^0.2.0 # modified transpose
  provider: ^5.0.0 # state management
  shared_preferences: ^2.0.6 # for persistence data. 1.Onboarding-seen-flag
  csv: ^5.0.0 # write csv for daily summaries
  starfruit: ^1.0.0+1 # correlation
  sqflite_migration: ^0.3.0 # database version update
  flutter_colorpicker: ^0.4.0 # todo ^ pick try later to upgrade again # color for label
  cupertino_icons: ^1.0.3 # iOS style
  flutter_datetime_picker: ^1.5.1 # new entry date selection
  syncfusion_flutter_charts: ^19.1.69+1 # scatter chart
  health: ^3.0.5
  fit_kit: ^1.1.2
  json_serializable: ^4.1.2
  json_annotation: ^4.0.1
  built_value: ^8.0.6




dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter



# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - ./assets/icon/logo_googlefit.png
  #    - ./assets/icon/who-96.png
  #    - ./assets/icon/who.svg
  #    - ./assets/icon/logo_rescueTime.png
  #    - ./assets/icon/logo_applehealth.png
  #    - ./assets/icon/logo_calendar.png
  #    - ./assets/icon/logo_facebook.png
  #    - ./assets/icon/logo_fitbit.png
  #    - ./assets/icon/logo_forecast.png
  #    - ./assets/icon/logo_garmin.png
  #    - ./assets/icon/logo_github.png
  #    - ./assets/icon/logo_lastfm.png
  #    - ./assets/icon/logo_oura.png
  #    - ./assets/icon/logo_pocket.png
  #    - ./assets/icon/logo_rescueTime.png
  #    - ./assets/icon/logo_strava.png
  #    - ./assets/icon/logo_todoist.png
  #    - ./assets/icon/logo_twitter.png
  #    - ./assets/icon/logo_withings.png


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
