name: insightme
description: Track anything about your life.

# The following defines the version and build number for your application.
version: 1.0.9+10

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: # SQLite
  path_provider: # SQLite
  file_picker: # csv file

  fl_animated_linechart: ^1.1.4 # linechart
  flutter_charts: ^0.2.0 # modified transpose
  provider: # state management
  shared_preferences: # for persistence data. 1.Onboarding-seen-flag
  csv: ^5.0.0 # write csv for daily summaries
  starfruit: ^1.0.0+1 # correlation
  sqflite_migration: ^0.3.0 # database version update
  flutter_colorpicker: 0.4.0 # todo ^ pick try later to upgrade again # color for label
  health: ^3.0.5
  fit_kit: ^1.1.2
  json_serializable: ^4.1.2
  json_annotation: ^4.0.1
  built_value: ^8.0.6




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:
  flutter_datetime_picker:
    git: # workaround https://github.com/Realank/flutter_datetime_picker/issues/197#issuecomment-725831759
      url: https://github.com/espresso3389/flutter_datetime_picker



dev_dependencies:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter



# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - ./assets/icon/who-96.png
    - ./assets/icon/who.svg
    - ./assets/icon/logo_googlefit.png
    - ./assets/icon/logo_rescueTime.png
    - ./assets/icon/logo_applehealth.png
    - ./assets/icon/logo_calendar.png
    - ./assets/icon/logo_facebook.png
    - ./assets/icon/logo_fitbit.png
    - ./assets/icon/logo_forecast.png
    - ./assets/icon/logo_garmin.png
    - ./assets/icon/logo_github.png
    - ./assets/icon/logo_lastfm.png
    - ./assets/icon/logo_oura.png
    - ./assets/icon/logo_pocket.png
    - ./assets/icon/logo_rescueTime.png
    - ./assets/icon/logo_strava.png
    - ./assets/icon/logo_todoist.png
    - ./assets/icon/logo_twitter.png
    - ./assets/icon/logo_withings.png
    #- images/a_dot_ham.jpeg


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
